CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 500 INCREMENT BY 1) PRIMARY KEY,
    user_id UUID UNIQUE NOT NULL,
    idp_id UUID UNIQUE,
    email TEXT,
    surname TEXT,
    given_name TEXT,
    date_of_birth DATE,
    city TEXT,
    address_line_1 TEXT,
    address_line_2 TEXT,
    region TEXT,
    country TEXT,
    postal_code TEXT
);