spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_LIQUIBASE_USER}
    password: ${DB_LIQUIBASE_USER_PASS}

  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: ${DB_SCHEMA}
    user: ${DB_LIQUIBASE_USER}
    password: ${DB_LIQUIBASE_USER_PASS}